// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

DTTable Computation(const DTTable &RG_combined_table);

#endif /* IT_computation_h */ 
