// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

DTTable Computation(const DTSet<DTPath3D> &BeadPositions,int Stride);

#endif /* IT_computation_h */ 
