// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"

DTTable Computation(double stride,const DTPath3D &BeadsPath);

#endif /* IT_computation_h */ 
