// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#include "computation.h"

#include "DTArguments.h"
#include "DTTimer.h"
#include "DTDataFile.h"
#include "DTError.h"

int main(int argc,const char *argv[])
{
    DTSetArguments(argc,argv);

    DTTable Rgyration;

    {
        // Inside a scope so that the input data file will be closed before the computation is called.
        DTDataFile variableDataFile;

        variableDataFile = DTDataFile("Rgyration.dtbin",DTFile::ReadOnly);
        Read(variableDataFile,"Rgyration",Rgyration);
    }

    DTDataFile outputFile("Output.dtbin",DTFile::NewReadWrite);

    //DTTimer timer;
    //timer.Start();
    Group output = Computation(Rgyration);

    //timer.Stop(); // Use timer.Time() to get the elapsed time
    if (DTHowManyErrors()>0) outputFile.Save(DTHowManyErrors(),"ErrorCount"); // For error logging

    WriteOne(outputFile,"Var",output);
    // The structure, to make it easy to open the output file
    Group::WriteStructure(outputFile,"SeqInfo_Var");
    outputFile.Save("Group","Seq_Var");

    // To speed up reading.
    outputFile.SaveIndex();

    return 0;
}
