// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"

DTTable Computation(const DTTable &table,const DTSet<DTPath3D> &chromosomes);

#endif /* IT_computation_h */ 
